feat: Added support for creating assignment for the programming language with submission type
torqbit/torqbit pull request #542
Opened 2024-12-16 11:44 UTC by shadab19it

![image](https://github.com/user-attachments/assets/01ec1323-2191-4ae2-ae5d-f4e7b4443dd6)

2024-12-16 12:46 UTC, shadab19it commented
![image](https://github.com/user-attachments/assets/23ba47cc-ab98-409f-9c4f-4dfbd36c227e)

2024-12-17 05:54 UTC, amezng requested changes

2024-12-17 05:54 UTC, amezng commented on src/types/courses/assignment.ts
> +
Use an interface - `ISubmissionConfig` and then extend it like 

```js
export interface ProgrammingProjectSubmission extends ISubmissionConfig {
  framework: string;
  versions: Map<string,string>;
  baseProjectArchiveUrl: string;
  }
  ```

2024-12-17 11:48 UTC, amezng approved these changes

2024-12-17 11:48 UTC, merged